version: "3.0"
services:
  tracker:
    build:
      context: .
      dockerfile: Dockerfile.tracker
    network_mode: "host"
    # ports:
    #   - "18000:8000/udp"
    #   - "18000:8000/tcp"

  seeder:
    build:
      context: .
      dockerfile: Dockerfile.seeder
    network_mode: "host"
    volumes:
      - ${PWD}/shared:/shared
      - ${PWD}/script:/script

  nginx:
    image: nginx
    volumes:
      - ${PWD}/html:/usr/share/nginx/html:ro
    ports:
      - "18080:80"
